Cisoreview release 4.3-dont merge
openshift/hypershift-toolkit pull request #109
Opened 2020-02-18 22:47 UTC by AkeemLaw

2020-02-19 23:01 UTC, relyt0925 commented on assets/ca-operator/ca-operator-deployment.yaml
> +    - configmaps
deployment

2020-02-19 23:01 UTC, relyt0925 commented on assets/ca-operator/ca-operator-deployment.yaml
> +  namespace:
no namespace field here

2020-02-20 01:36 UTC, relyt0925 commented on assets/ca-operator/ca-operator-deployment.yaml
> +  - deployment
deployments instead of deployment

2020-02-27 19:45 UTC, relyt0925 requested changes
this should be closed

2020-03-02 20:33 UTC, closed without merging

2020-03-02 20:34 UTC, AkeemLaw commented
Another PR already addressed the issue