Add cluster version
openshift/hypershift-toolkit pull request #126
Opened 2020-02-26 21:39 UTC by AkeemLaw

2020-02-26 21:41 UTC, csrwng commented
@AkeemLaw pls run `make` so you can update bindata.go

2020-02-26 22:26 UTC, csrwng commented
/ok-to-test

2020-02-27 05:52 UTC, relyt0925 requested changes
We are still testing this as well to fix something small in the openshift console. Will approve when tests pass

2020-03-07 23:08 UTC, relyt0925 commented
/close

2020-03-07 23:08 UTC, closed without merging